DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS GENRES;

DROP TABLE IF EXISTS AUTHORS;

DROP SEQUENCE IF EXISTS SQ_BOOKS;
CREATE SEQUENCE SQ_BOOKS START WITH 1;

DROP SEQUENCE IF EXISTS SQ_GENRES;
CREATE SEQUENCE SQ_GENRES START WITH 1;

DROP SEQUENCE IF EXISTS SQ_AUTHORS;
CREATE SEQUENCE SQ_AUTHORS START WITH 1;

CREATE TABLE GENRES(
    ID BIGINT DEFAULT NEXT VALUE FOR SQ_GENRES NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORS(
    ID BIGINT DEFAULT NEXT VALUE FOR SQ_AUTHORS NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS(
    ID BIGINT DEFAULT NEXT VALUE FOR SQ_BOOKS NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL ,
    CONSTRAINT FK_BOOKS_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES,
    CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS
);
