server:
  port: 8080

spring:
  banner:
    location: banner.txt
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: classpath:/schema.sql

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 3000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000


management:
  endpoints:
    web:
      exposure:
        include: "*"



logging:
  level:
    org:
      springframework:
        web: trace

