DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS GENRES;

DROP TABLE IF EXISTS AUTHORS;

DROP SEQUENCE IF EXISTS SQ_BOOKS;

CREATE SEQUENCE SQ_BOOKS START WITH 1;

CREATE TABLE GENRES
(
    ID   BIGINT       NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)       NOT NULL
);

CREATE TABLE BOOKS
(
    ID        BIGINT DEFAULT NEXT VALUE FOR SQ_BOOKS NOT NULL PRIMARY KEY,
    NAME      VARCHAR(255)                           NOT NULL,
    GENRE_ID  BIGINT                                 NOT NULL,
    AUTHOR_ID BIGINT                                 NOT NULL,
    CONSTRAINT FK_BOOKS_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES,
    CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS
);

DROP SEQUENCE IF EXISTS SQ_BOOK_COMMENTS;
CREATE SEQUENCE SQ_BOOK_COMMENTS START WITH 1;

CREATE TABLE COMMENTS
(
    ID      BIGINT DEFAULT NEXT VALUE FOR SQ_BOOK_COMMENTS NOT NULL PRIMARY KEY,
    BOOK_ID BIGINT                                         NOT NULL,
    TEXT    VARCHAR2(255),
    CONSTRAINT FK_COMMENTS_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS ON DELETE CASCADE
);

CREATE INDEX IDX_COMMENTS$BOOK ON COMMENTS(BOOK_ID);

DROP TABLE IF EXISTS USERS;
DROP SEQUENCE IF EXISTS SQ_USERS;

CREATE SEQUENCE SQ_USERS START WITH 1;
CREATE TABLE USERS
(
    ID   BIGINT DEFAULT NEXT VALUE FOR SQ_USERS PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    CONSTRAINT UI_USERS$USERNAME UNIQUE (USERNAME)
);

