CREATE SEQUENCE IF NOT EXISTS SQ_GENRES START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SQ_AUTHORS START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SQ_BOOKS START WITH 1;

DROP TABLE IF EXISTS TMP_GENRES_MIGRATE;
DROP TABLE IF EXISTS TMP_AUTHORS_MIGRATE;
DROP TABLE IF EXISTS TMP_BOOKS_MIGRATE;

CREATE TEMPORARY TABLE TMP_GENRES_MIGRATE
(
    ID     bigint not null default nextval('SQ_GENRES') primary key,
    OLD_ID varchar(255) not null unique,
    NAME   VARCHAR(255) NOT NULL
) ON COMMIT PRESERVE ROWS;

CREATE TEMPORARY TABLE TMP_AUTHORS_MIGRATE
(
    ID     bigint not null default nextval('SQ_AUTHORS') primary key,
    OLD_ID varchar(255) not null unique,
    NAME   VARCHAR(255) NOT NULL
) ON COMMIT PRESERVE ROWS;

CREATE TEMPORARY TABLE TMP_BOOKS_MIGRATE
(
    ID        bigint not null default nextval('SQ_BOOKS') primary key,
    OLD_ID    varchar(255) not null unique,
    NAME      VARCHAR(255) NOT NULL,
    GENRE_ID  VARCHAR(255) NOT NULL,
    AUTHOR_ID VARCHAR(255) NOT NULL
) ON COMMIT PRESERVE ROWS;