server:
  port: 8080

spring:
  banner:
    location: banner.txt

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    password: postgres
    username: postgres

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: classpath:/schema.sql


logging:
  level:
    org:
      springframework:
        web: trace

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: always

