DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS GENRES;

DROP TABLE IF EXISTS AUTHORS;

DROP TABLE IF EXISTS COMMENTS;


CREATE TABLE GENRES
(
    ID   BIGSERIAL    NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORS
(
    ID   BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)          NOT NULL
);

CREATE TABLE BOOKS
(
    ID        BIGSERIAL    NOT NULL PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    GENRE_ID  BIGINT       NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    CONSTRAINT FK_BOOKS_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES,
    CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID      BIGSERIAL NOT NULL PRIMARY KEY,
    BOOK_ID BIGINT    NOT NULL,
    TEXT    VARCHAR(255),
    CONSTRAINT FK_COMMENTS_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS ON DELETE CASCADE
);

CREATE INDEX IDX_COMMENTS$BOOK ON COMMENTS (BOOK_ID);
