spring:
  banner:
    location: banner.txt

  data:
    mongodb:
      database: otus
      host: 127.0.0.1
      port: 27018
      username: mongoadmin
      password: secret
      authentication-database: admin

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.books.mongock.changelog



