DROP TABLE IF EXISTS BOOKS;

DROP TABLE IF EXISTS GENRES;

DROP TABLE IF EXISTS AUTHORS;

DROP SEQUENCE IF EXISTS SQ_BOOKS;

CREATE SEQUENCE SQ_BOOKS START WITH 1;

CREATE TABLE GENRES(ID BIGINT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL );

CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY NOT NULL, NAME VARCHAR(255) NOT NULL );

CREATE TABLE BOOKS(
    ID BIGINT DEFAULT NEXT VALUE FOR SQ_BOOKS NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL ,
    CONSTRAINT FK_BOOKS_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES,
    CONSTRAINT FK_BOOKS_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS
);
